window.controlRoomData = {
  readiness: [
    { label: "Backend architecture", value: 72, note: "Core records, rules, integrations, workflows, and verification are documented." },
    { label: "Product research", value: 82, note: "Top 100 and top 30 sample pack are defined." },
    { label: "Supplier/sample readiness", value: 42, note: "Routes exist, but real supplier links and samples are missing." },
    { label: "Compliance readiness", value: 46, note: "Lanes and gates exist; proof is not gathered." },
    { label: "CRM and marketing", value: 58, note: "Data model, flows, incentives, and lead magnets exist; live setup is missing." },
    { label: "Live account setup", value: 0, note: "Shopify, supplier apps, payment, tax, and email accounts are not connected." },
    { label: "Visual verification", value: 10, note: "Dashboard exists; live Shopify, emails, checkout, and product pages still need checks." }
  ],
  architecture: [
    { name: "Product catalogue", status: "Designed", detail: "Products, variants, lanes, product files, claims, and publish gates are mapped." },
    { name: "Supplier management", status: "Designed", detail: "Supplier routes and backup routes exist, but live supplier links are missing." },
    { name: "US and UK markets", status: "Designed", detail: "Market eligibility, currency, duties, tax, and product rules are separated." },
    { name: "Pricing and margin", status: "Designed", detail: "Margin rules exist. Real landed costs still need sample supplier data." },
    { name: "Order fulfilment", status: "Designed", detail: "Payment, fraud, market, customs, supplier routing, tracking, and exceptions are mapped." },
    { name: "CRM and email", status: "Designed", detail: "Lead capture, consent, segments, lifecycle flows, and incentives are mapped." },
    { name: "Trend intelligence", status: "Designed", detail: "Monthly scoring, sample recommendations, and dashboard outputs are defined." },
    { name: "Live commerce setup", status: "Missing", detail: "Shopify, supplier apps, payment, tax, and analytics accounts are still needed." }
  ],
  samples: [
    { rank: 1, id: "beauty-001", product: "Travel cosmetic/toiletry organizer", lane: "Lane 1", decision: "Direct-sale priority", route: "CJdropshipping", backup: "DSers/AppScenic", score: 33, demand: "Steady/seasonal", status: "Not ordered" },
    { rank: 2, id: "beauty-002", product: "Satin bonnet/scrunchie/headband set", lane: "Lane 1", decision: "Direct-sale priority", route: "EPROLO", backup: "DSers/CJdropshipping", score: 33, demand: "Trending/steady", status: "Not ordered" },
    { rank: 3, id: "beauty-003", product: "Heatless curl set", lane: "Lane 1", decision: "Direct-sale priority", route: "DSers", backup: "CJdropshipping/EPROLO", score: 32, demand: "Viral/steady", status: "Not ordered" },
    { rank: 4, id: "beauty-004", product: "Makeup headband and wrist wash-band set", lane: "Lane 1", decision: "Direct-sale priority", route: "DSers", backup: "CJdropshipping", score: 32, demand: "Viral/steady", status: "Not ordered" },
    { rank: 5, id: "beauty-005", product: "Resin claw clips", lane: "Lane 1", decision: "Direct-sale priority", route: "DSers", backup: "CJdropshipping/EPROLO", score: 32, demand: "Trending/steady", status: "Not ordered" },
    { rank: 6, id: "beauty-006", product: "Rotating makeup organizer", lane: "Lane 1", decision: "Direct-sale priority", route: "CJdropshipping", backup: "DSers/AppScenic", score: 31, demand: "Steady", status: "Not ordered" },
    { rank: 7, id: "beauty-013", product: "Scalp shampoo brush", lane: "Lane 2", decision: "Sample first", route: "CJdropshipping", backup: "DSers/Syncee", score: 31, demand: "Viral/steady", status: "Not ordered" },
    { rank: 8, id: "beauty-007", product: "Silicone brush cleaning mat/rack", lane: "Lane 1", decision: "Direct-sale priority", route: "DSers", backup: "CJdropshipping", score: 31, demand: "Steady", status: "Not ordered" },
    { rank: 9, id: "beauty-008", product: "Travel makeup brush case/covers", lane: "Lane 1", decision: "Direct-sale priority", route: "DSers", backup: "CJdropshipping", score: 31, demand: "Steady", status: "Not ordered" },
    { rank: 10, id: "beauty-009", product: "Microfiber hair towel wrap", lane: "Lane 1", decision: "Direct-sale priority", route: "CJdropshipping", backup: "DSers/EPROLO", score: 30, demand: "Steady", status: "Not ordered" },
    { rank: 11, id: "beauty-010", product: "Spa wrist wash bands", lane: "Lane 1", decision: "Direct-sale priority", route: "DSers", backup: "CJdropshipping", score: 30, demand: "Viral/steady", status: "Not ordered" },
    { rank: 12, id: "beauty-011", product: "Triangle powder puff set", lane: "Lane 2", decision: "Sample first", route: "DSers", backup: "CJdropshipping", score: 30, demand: "Steady", status: "Not ordered" },
    { rank: 13, id: "beauty-014", product: "Acrylic lipstick holder", lane: "Lane 1", decision: "Direct-sale priority", route: "CJdropshipping", backup: "DSers/AppScenic", score: 30, demand: "Steady", status: "Not ordered" },
    { rank: 14, id: "beauty-012", product: "Reusable makeup remover pads", lane: "Lane 2", decision: "Sample first", route: "CJdropshipping", backup: "DSers/Syncee", score: 29, demand: "Steady", status: "Not ordered" },
    { rank: 15, id: "beauty-016", product: "Oversized bow hair clip", lane: "Lane 1", decision: "Direct-sale priority", route: "EPROLO", backup: "DSers/CJdropshipping", score: 29, demand: "Trending", status: "Not ordered" },
    { rank: 16, id: "beauty-015", product: "Bandana/scarf hair accessory set", lane: "Lane 1", decision: "Direct-sale priority", route: "EPROLO", backup: "DSers/Trendsi watchlist", score: 29, demand: "Trending/seasonal", status: "Not ordered" },
    { rank: 17, id: "beauty-017", product: "Elasticated headband set", lane: "Lane 1", decision: "Direct-sale priority", route: "DSers", backup: "EPROLO/CJdropshipping", score: 29, demand: "Trending/steady", status: "Not ordered" },
    { rank: 18, id: "beauty-018", product: "Makeup sponge air-dry holder", lane: "Lane 1", decision: "Direct-sale priority", route: "DSers", backup: "CJdropshipping", score: 28, demand: "Steady", status: "Not ordered" },
    { rank: 19, id: "beauty-019", product: "Lash/brow spoolie set", lane: "Lane 2", decision: "Sample first", route: "DSers", backup: "CJdropshipping/Syncee", score: 28, demand: "Steady", status: "Not ordered" },
    { rank: 20, id: "beauty-020", product: "Edge brush and parting comb kit", lane: "Lane 1", decision: "Direct-sale priority", route: "CJdropshipping", backup: "DSers", score: 28, demand: "Steady", status: "Not ordered" },
    { rank: 21, id: "beauty-021", product: "Satin sleep eye mask", lane: "Lane 1", decision: "Direct-sale priority", route: "EPROLO", backup: "DSers/CJdropshipping", score: 28, demand: "Steady", status: "Not ordered" },
    { rank: 22, id: "beauty-022", product: "Hair turban towel", lane: "Lane 1", decision: "Direct-sale priority", route: "CJdropshipping", backup: "DSers/EPROLO", score: 28, demand: "Steady", status: "Not ordered" },
    { rank: 23, id: "beauty-023", product: "Clear TSA cosmetic bag set", lane: "Lane 1", decision: "Direct-sale priority", route: "CJdropshipping", backup: "DSers/AppScenic", score: 28, demand: "Steady/seasonal", status: "Not ordered" },
    { rank: 24, id: "beauty-024", product: "Cosmetic mixing palette/spatula", lane: "Lane 2", decision: "Sample first", route: "DSers", backup: "CJdropshipping/Syncee", score: 27, demand: "Steady", status: "Not ordered" },
    { rank: 25, id: "beauty-025", product: "Perfume atomizer", lane: "Lane 1", decision: "Direct-sale priority", route: "CJdropshipping", backup: "DSers", score: 27, demand: "Steady/travel", status: "Not ordered" },
    { rank: 26, id: "beauty-026", product: "Lighted compact mirror", lane: "Lane 4", decision: "Sample first", route: "AppScenic document-led supplier", backup: "CJdropshipping documented supplier", score: 27, demand: "Steady", status: "Not ordered" },
    { rank: 27, id: "beauty-027", product: "LED vanity mirror", lane: "Lane 4", decision: "Sample first", route: "AppScenic document-led supplier", backup: "Authorized/documented supplier", score: 26, demand: "Steady", status: "Not ordered" },
    { rank: 28, id: "beauty-028", product: "Brow shaping stencil kit", lane: "Lane 1", decision: "Direct-sale priority", route: "DSers", backup: "CJdropshipping", score: 26, demand: "Steady", status: "Not ordered" },
    { rank: 29, id: "beauty-029", product: "False eyelash applicator kit", lane: "Lane 2", decision: "Sample first", route: "DSers", backup: "CJdropshipping/Syncee", score: 26, demand: "Steady", status: "Not ordered" },
    { rank: 30, id: "beauty-030", product: "Empty travel cosmetic containers", lane: "Lane 1", decision: "Direct-sale priority", route: "CJdropshipping", backup: "DSers/AppScenic", score: 26, demand: "Steady/travel", status: "Not ordered" }
  ],
  crmFlows: [
    "Welcome and lead magnet delivery",
    "First-purchase incentive",
    "Weekly product newsletter",
    "New arrival alert",
    "Abandoned cart recovery",
    "Post-purchase education",
    "Review request",
    "Cross-sell and bundle",
    "Winback"
  ],
  leadMagnets: [
    "7-Day Beauty Organization Reset",
    "Travel Beauty Packing Checklist",
    "Heatless Hair Routine Cheat Sheet",
    "Brush Cleaning And Replacement Calendar"
  ],
  trendWeights: [
    ["Demand growth", 15],
    ["Steady demand", 10],
    ["Profit potential", 15],
    ["Supplier depth", 10],
    ["Operational fit", 10],
    ["Compliance ease", 10],
    ["Content potential", 10],
    ["Customer signal", 10],
    ["US/UK fit", 5],
    ["Differentiation", 5]
  ],
  trendOutputs: [
    "Top 20 product opportunities",
    "Top 10 sample recommendations",
    "Top 10 newsletter topics",
    "Products to pause or remove",
    "Bundle opportunities",
    "US vs UK market notes",
    "Supplier and margin risk notes"
  ],
  missing: [
    "Shopify account and store settings",
    "Supplier accounts and real product links",
    "Top 30 sample orders placed",
    "Sample photos and inspection notes",
    "US sales tax and UK VAT approach",
    "Duties/import-tax setup",
    "USD and GBP landed cost review",
    "Payment setup",
    "Lead magnet PDF content",
    "Email sender and unsubscribe setup",
    "Product import files",
    "Live visual verification for product pages, checkout, emails, and admin screens"
  ]
};
